# DSO109 Python : Lesson Nine Companion Notebook

### Table of Contents <a class="anchor" id="DS109L9_toc"></a>

* [Table of Contents](#DS109L9_toc)
    * [Page 1 - Introduction](#DS109L9_page_1)
    * [Page 2 - Numpy Arrays](#DS109L9_page_2)
    * [Page 3 - Aggregate Functions on Arrays](#DS109L9_page_3)
    * [Page 4 - Data Generation with NumPy](#DS109L9_page_4)
    * [Page 5 - Arithmetic with Arrays](#DS109L9_page_5)
    * [Page 6 - Indexing on Arrays](#DS109L9_page_6)
    * [Page 7 - Creating Matrices with Arrays](#DS109L9_page_7)
    * [Page 8 - Matrix Arithmetic and Aggregation](#DS109L9_page_8)
    * [Page 9 - Matrix Indexing](#DS109L9_page_9)
    * [Page 10 - Aggregating Matrix Values Across Columns and Rows](#DS109L9_page_10)
    * [Page 11 - Manipulating Matrices](#DS109L9_page_11)
    * [Page 12 - Key Terms](#DS109L9_page_12)
    * [Page 13 - Lesson 9 Hands-On](#DS109L9_page_13)
    

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 1 - Introduction<a class="anchor" id="DS109L9_page_1"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

In [1]:
from IPython.display import VimeoVideo
# Tutorial Video Name: NumPy
VimeoVideo('390082803', width=720, height=480)


The transcript for the above overview video **[is located here](https://repo.exeterlms.com/documents/V2/DataScience/Video-Transcripts/DSO109L09overview.zip)**.

# Introduction

Another package that data scientists frequently use in Python is NumPy, which includes functions for mathematics basics and the data types of arrays and matrices.  In this lesson, you will learn how to: 

* Create NumPy arrays and matrices
* Run aggregate functions on arrays and matrices
* Index on arrays and matrices
* Perform arithmetic upon arrays and matrices
* Generate data with NumPy
* Manipulate the shape of matrices

This lesson will culminate in a hands-on in which you practice your array and matrix skills with arrays and matrices of your own making.

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Additional Info!</h3>
    </div>
    <div class="panel-body">
        <p>You may want to watch this <a href="https://vimeo.com/460783739"> recorded live workshop </a> that goes over the material in this lesson. </p>
    </div>
</div>


<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 2 - Numpy Arrays<a class="anchor" id="DS109L9_page_2"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Numpy Arrays

The second most often used data science package in Python is *Numpy*, a combination of "numbers" and "Python." NumPy was the original mathematical Python package, and it is the backbone of many of the machine learning packages, so it is very important to have a good understanding of NumPy. To work with NumPy, you will need to import the package into your Jupyter Notebook, using this line of code:

```python
import numpy as np
```

This is telling Python that you are importing the `numpy` package, and you want to nickname it `np` to shorten things up.  `np` is the standard abbreviation for NumPy, though you could technically abbreviate it anything you'd like. 

---

## Arrays

While `pandas` deals with DataFrames, the data format that NumPy makes use of is called an array. What is an array? Simply a list of numbers that has been turned into its own variable so that you can use it as a chunk (all the data together) rather than one at a time (each number in the list). How about you make your first NumPy array?

```python
my_first_array = np.array([7,2,1])
```

You are giving this array the name `my_first_array`, and it contains the numbers 7, 2, and 1.  The function to do this is `np.array()`. 

Now, if you call that array, by simply typing in it's name again, you will get this output:

```text
array([7, 2, 1])
```

It tells you the format of the data (an array), and then gives you information about what data is in that array.  

You can also print arrays - try it:

```python
print(my_first_array)
```

When printed, the data architecture (array) is left off, and you only get the data in the array, like this:

```text
[7 2 1]
```

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 3 - Aggregate Functions on Arrays<a class="anchor" id="DS109L9_page_3"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Aggregate Functions on Arrays

You can run aggregate functions on arrays - things like getting measures of central tendency, dispersion, or sums.  Try it out! 

---

## Max

To find the max value in your array, simply use the function `.max()`: 

```python
my_first_array.max()
```

The result is `7`!

---

## Min

To find the minimum value in your array, you can use the function `.min()`, like this:

```python
my_first_array.min()
```

The result is `1`!

---

## Mean

You can also find the mean, using the function `.mean()` on your array: 

```python
my_first_array.mean()
```

And here is the output:

```text
3.3333333333333335
```

---

## Standard Deviation

The standard deviation is another aggregate function option.  Try out `.std()`:

```python
my_first_array.std()
```

The result is this:

```text
2.6246692913372702
```

---

## Sum

The last option for performing aggregate functions on arrays is `.sum()`, which totals everything for you:

```python
my_first_array.sum()
```

The result is `10`. 

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Additional Info!</h3>
    </div>
    <div class="panel-body">
        <p>Want to know more about array aggregate functions? Check out <a href="https://jakevdp.github.io/PythonDataScienceHandbook/02.04-computation-on-arrays-aggregates.html"> this reference to ALL aggregate functions, their companions that will work even with missing data, and even examples of how aggregate functions can be used. </a></p>
    </div>
</div>

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 4 - Data Generation with NumPy<a class="anchor" id="DS109L9_page_4"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Data Generation with NumPy

There are many different ways to generate data with NumPy.  

---

## Generating Random Numbers

Perhaps the most useful way to generate data is to generate random numbers for simulation. You can use the function `random.random()` to generate an array filled with random numbers, and the argument that goes in the parentheses is the number of random numbers you want to generate in your array.  It's the length of your array. Here's an example:

```python
RandomNumbers = np.random.random(1)
```

The code above generates an array named `RandomNumbers` that is only one digit long.  Take a look when you call it:

```text
array([0.20739175])
```

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Tip!</h3>
    </div>
    <div class="panel-body">
        <p>Remember that since this generates a random number, there's a good chance that your number won't be the same one that you see up above. Don't worry if you get a different result.</p>
    </div>
</div>

---

## Generating Specific Numbers

You also have the option to fill your array with a particular number.  The function `ones()` generates an array of the number one.  The function `zeros()` generates an array filled with the number zero. Check 'em out! 

---

### Generating Ones

```python
allOnes = np.ones(7)
```

The code above generates an array with a length of seven that are all ones, in an array named `allOnes`:

```text
array([1., 1., 1., 1., 1., 1., 1.])
```

---

### Generating Zeroes 

And the code below will generate an array named `allZeroes` with a length of two, in an array with a length of two:

```python
allZeroes = np.zeros(2)
```

The result:

```text
array([0., 0.])
```

Being able to do this can be quite useful, because you will often use the numbers one and zero as placeholders for dichotomous, or two category, variables.  Things like "yes/no", "men/women", "child/adult" etc. may all be represented as zeros and ones.

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 5 - Arithmetic with Arrays<a class="anchor" id="DS109L9_page_5"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Arithmetic with Arrays

You can also do arithmetic with arrays, with the four basic math operations. This arithmetic can be array to array, or can be a single number applied to every number in the array.  Numpy automatically iterates things for you, so you don't have to worry about looping anything in your array.  That speeds things up considerably!

---

## Arithmetic with Two Arrays

You'll start with doing arithmetic on two arrays.  This works, as long as your arrays aren't the same length. Start by creating a second array, also three in length:

```python
my_second_array = np.array([1,2,7])
```

---

### Adding

Then you can add them together, easily by just using the plus sign:

```python
my_first_array + my_second_array
```

Here is the result - a third array, where every number is the sum of the first and the second array:

```text
array([8, 4, 8])
```

If you're feeling doubtful, try it longhand yourself once.  `my_first_array` contains the values 7, 2, and 1.  `my_second_array` contains the values 1, 2, and 7.  So, 7 (from the first array) plus 1 (from the second array) is 8.  Similarly, 2 from the first array and 2 from the second array make 4.  Lastly, 1 from the first array and 7 from the second array added together make 8 once more.

Just like anything else, you can assign your addition to a variable, like this:

```python
ArraySummed = my_first_array + my_second_array
```

Then call it - `ArraySummed` - to get your result.

---

### Subtracting

The same principle holds true for doing subtraction with two arrays. This will subtract the second array from the first:

```python
ArraySubtracted = my_first_array - my_second_array
```

And here is the result once you call `ArraySubtracted`:

```text
array([ 6,  0, -6])
```

---

### Multiplying

Multiplication is also possible with two arrays: 

```python
ArrayMultiplied = my_first_array * my_second_array
```

The resultant product shows itself once you call `ArrayMultiplied`:

```text
array([7, 4, 7])
```

---

### Dividing 

Lastly, you can also divide arrays. The code below will do so:

```python
ArrayDivided = my_first_array / my_second_array
```

And here is the result:

```text
ArrayDivided
```

---

## Arithmetic on an Array

It is also possible to do arithmetic on just one array.  Say you'd like to see your array with every variable multiplied by four? It can be done without a lot of fuss.  Again, no need to loop - just use your operand on the array name!

---

### Multiplying

How about multiplying `my_first_array` by four?

```python
TimesFour = my_first_array * 4
```

Here is the product when `TimesFour` is called:

```text
array([28,  8,  4])
```

---

### Dividing

You can also divide every number in the array by four:

```python
DividedFour = my_first_array / 4
```

And the result:

```text
array([1.75, 0.5 , 0.25])
```

---

### Adding

It's relatively to add four to every number as well:

```python
PlusFour = my_first_array + 4
```

With this result:

```text
array([11,  6,  5])
```

---

### Subtracting

Or to subtract four from everything in your array:

```python
MinusFour = my_first_array - 4
```

Here's what you get when you call `MinusFour`:

```text
array([ 3, -2, -3])
```

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 6 - Indexing on Arrays<a class="anchor" id="DS109L9_page_6"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


Indexing on Arrays

You can access certain elements in an array by using indexing. The thing to remember about indexing is that Python is *zero index*, meaning that you start counting the number positions from zero, and not from one. In brackets you will place the position numbers you want.  If you just want a single number, then you can call the array and then place the number of the position. 

For instance, for `my_first_array`, shown below:

```text
array([7, 2, 1])
```

You can get the first place by calling `[0]` at the end of the name, like this:

```python
my_first_array[0]
```

Which will yield the number `7` in return.

---

## Accessing Multiple Numbers in an Array

If you want to access multiple numbers in an array, then you can use two position numbers, separated by a colon.  So the format will read `[position a #: position b #]`. You will receive everything inclusive of those numbers.  For instance, if you wanted to get everything in the current array, you could try something like this:

```python
my_first_array[0:3]
```

Which will yield this:

```text
array([7, 2, 1])
```

You can also leave a position number missing, instead making use of just the colon.  Just a colon without a position means "everything." For instance, if you wanted all the numbers after the second position, you could use this notation:

```python
my_first_array[1:]
```

With the resulting information retrieved:

```text
array([2, 1])
```

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 7 - Creating Matrices with Arrays<a class="anchor" id="DS109L9_page_7"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Creating Matrices with Arrays

Matrices are the back bone for a lot of the more complex statistical analyses and machine learning algorithms, which often make use of matrix algebra at their heart. While you won't need to know how to do that math (hoorah!), you will need to know how to create matrices with arrays. In the simplest terms, making a matrix out of arrays just involves placing array lists together, separated by a comma, like this:

```python
my_first_matrix = np.array([[8,9], [5,4]])
```

When you call `my_first_matrix`, it should now look like this:

```text
array([[8, 9],
       [5, 4]])
```

Having the arrays on multiple lines is a visual way to double check that you do in fact have a matrix instead of an array.

---

## Matrix of All Ones

You can use the same data generation effects on matrices that you can on arrays. For instance, you can create a matrix of all ones. The below code will make a matrix filled with ones that has seven rows and two columns:

```python
AllOnesMatrix = np.ones((7,2))
```

And here's what that will look like when you call `AllOnesMatrix`:

```text
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])
```

---

## Matrix of All Zeros

You can do the exact same thing, but with zeros if you'd like: 

```python
AllZeroesMatrix = np.zeros((7,2))
```

Again, the above text creates a matrix of 7 rows and 2 columns:

```text
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])
```

---

## Random Matrix

Lastly, you can also make a random matrix, using the `np.random.random` function:

```python
RandomMatrix = np.random.random((7,2))
```

And here is an example of what that random matrix might look like, though of course, because it is random, yours will most likely have different numbers!

```text
array([[0.06528685, 0.9767537 ],
       [0.61912473, 0.02705559],
       [0.78753624, 0.04548327],
       [0.53897846, 0.11152877],
       [0.86995997, 0.81987622],
       [0.63686912, 0.4906349 ],
       [0.41159298, 0.29468443]])
```

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 8 - Matrix Arithmetic and Aggregation<a class="anchor" id="DS109L9_page_8"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Matrix Arithmetic and Aggregation

Yes, you can do arithmetic and aggregate functions on matrices as well! Commence the partying!

---

## Arithmetic

To perform basic arithmetic on matrices, simply call their names and separate by the arithmetic operator of choice. The below code will add the randomly generated matrix (`RandomMatrix`) and the `AllOnesMatrix` together:

```python
RandomMatrix + AllOnesMatrix
```

And here is your resultant new matrix:

```text
array([[1.06528685, 1.9767537 ],
       [1.61912473, 1.02705559],
       [1.78753624, 1.04548327],
       [1.53897846, 1.11152877],
       [1.86995997, 1.81987622],
       [1.63686912, 1.4906349 ],
       [1.41159298, 1.29468443]])
```

You can also subtract, divide, and multiply matrices this way.

---

## Aggregation

You can also make use of the aggregation functions you learned for arrays - simply call them on a matrix instead.  For instance, to get the minimum value for `my_first_matrix`, use the `.min()` function:

```python
my_first_matrix.min()
```

And you receive the value of `4`.  You can make use of the others as well:

```python
my_first_matrix.max()
my_first_matrix.sum()
my_first_matrix.mean()
my_first_matrix.std()
```

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 9 - Matrix Indexing<a class="anchor" id="DS109L9_page_9"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


# Matrix Indexing

You can access elements in a matrix through indexing. Simply call the matrix name, and then use square brackets to indicate the row and column in question.  The first number in square brackets will be the row, and the second number in square brackets after the comma will be the column where your element is located.  For instance, for `my_first_matrix`, which has the following values:

```text
array([[8, 9],
       [5, 4]])
```

If you want to access the `9`, then you would want to use the following code:

```python
my_first_matrix[0,1]
```

The 0 stands for the first row (remember, Python is zero-index!) and the 1 stands for the second column, which is where the `9` is located. If you run the code, you should receive back the number `9`.

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 10 - Aggregating Matrix Values Across Columns and Rows<a class="anchor" id="DS109L9_page_10"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Aggregating Matrix Values Across Columns and Rows

Since a matrix now takes the form of columns and rows, you can also do aggregate functions along the columns and rows.

Remember `my_first_matrix`? 

```text
array([[8, 9],
       [5, 4]])
```

How about you find the largest number in the columns?

```python
my_first_matrix.max(axis=0)
```

You will use the aggregate function you want (in this case, `.max()`), but then go one step further, and specify the argument `axis=` to ensure that you aren't doing it for the whole matrix, but rather for either columns or rows.  `axis=0` is for columns, and `axis=1` is for rows.

Here is the result of the above code:

```text
array([8, 9])
```

You'll note that it spits back two numbers, not just one.  That is because there are two columns in your matrix, and it gives the largest number for each column.  In the first column, eight is the biggest number (8 > 5), and in the second column, nine is the largest number (9 > 4).  You can similarly do this for the rows, instead of the columns:

```python
my_first_matrix.max(axis=1)
```

Just by changing the `0` to a `1` after `axis=`, you now get different results, finding the largest number in a row:

```text
array([9, 5])
```

Again, you receive two numbers.  The first is for the largest number in the first row (9), and the second is for the largest number in the second row (5).

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 11 - Manipulating Matrices<a class="anchor" id="DS109L9_page_11"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Manipulating Matrices

The last thing you'll learn to do with matrices is to manipulate them - basically, change their shape.

---

## Transposing 

First, you'll learn to transpose matrices. What does *transpose* mean? It means to flip your data.  It's easier to get a visual on it.  Here is the original ```AllOnesMatrix```:

```text
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])
```

And once it has been transposed, it will look like this:

```text
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])
```

The code for doing this is one simple little letter - `.T`. So the code to flip the `AllOnesMatrix` looks like this:

```python
AllOnesMatrix.T
```

---

## Reshaping

You can also reshape your matrix. What if you want to take that matrix and put it in one column of 14 rows? That can be done with the `reshape()` function, and the arguments you'll use inside the parentheses is the number of rows, separated by a comma and followed by the number of columns.  Here's what the code to reshape `AllOnesMatrix` to a single column with 14 rows looks like:

```python
AllOnesMatrix.reshape(14,1)
```

And here's the resulting format:

```text
array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])
```

You can reshape any number of different ways, but remember that the number has to be divisible by the total number of elements.  So, trying this:

```python
AllOnesMatrix.reshape(3,5)
```

Won't work, and you'll get this error:

```text
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-68-f20be8614c6b> in <module>()
----> 1 AllOnesMatrix.reshape(3,5)

ValueError: cannot reshape array of size 14 into shape (3,5)
```

That is because 3 times 5 is 15, not 14...and so Python doesn't know what to do with that extra number.  It can't be easily placed into the new matrix format. As you enter into machine learning, which is based on arrays and matrices, you may encounter this error sometimes - so it's good to be armed with knowledge of what it's all about!

---

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 12 - Key Terms <a class="anchor" id="DS109L9_page_12"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Key Terms 

Below is a list and short description of the important keywords learned in this lesson. Please read through and go back and review any concepts you do not fully understand. Great Work!

<table class="table table-striped">
    <tr>
        <th>Keyword</th>
        <th>Description</th>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>NumPy</td>
        <td>Python package designed for mathematics, arrays, and matrices.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>Array</td>
        <td>List of numbers.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>Zero Index</td>
        <td>Start counting positions from zero.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>Matrix</td>
        <td>Multiple arrays together; made up of columns and rows.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>Transpose</td>
        <td>Go from a horizontal to vertical shape of your data.</td>
    </tr>
</table>

---

## Key NumPy Code

<table class="table table-striped">
    <tr>
        <th>Keyword</th>
        <th>Description</th>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>np.array()</td>
        <td>Generates an array.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.max()</td>
        <td>Finds the maximum value.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.min()</td>
        <td>Finds the smallest value.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.mean()</td>
        <td>Finds the mean.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.std()</td>
        <td>Finds the standard deviation.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.sum()</td>
        <td>Adds everything together for the total.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>np.random.random()</td>
        <td>Generates random numbers between zero and one.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>np.ones()</td>
        <td>Generates ones.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.zeros()</td>
        <td>Generates zeros.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>axis=0</td>
        <td>Argument for an aggregate function that specifies to perform the action on columns.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>axis=1</td>
        <td>Argument for an aggregate function that specifies to perform the action on rows.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.T()</td>
        <td>Transposes a matrix.</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" nowrap>.reshape()</td>
        <td>Changes the shape of a matrix.</td>
    </tr>
</table>

<hr style="height:10px;border-width:0;color:gray;background-color:gray">

# Page 13 - Lesson 9 Hands-On<a class="anchor" id="DS109L9_page_13"></a>

[Back to Top](#DS109L9_toc)

<hr style="height:10px;border-width:0;color:gray;background-color:gray">


For your Lesson 9 Hands-On, you will be practicing your new skills with arrays and matrices! This Hands-On **will** be graded, so be sure you complete all requirements.

Please complete the following tasks in a Jupyter Notebook file, using the `numpy` package: 

* Create a five element array using your favorite numbers named `myFavorites`.
* Perform each of the five aggregate functions on your array.
* Create a five element array containing only ones named `OneArrayToRuleThemAll`.
* Add `myFavorites` and `OneArrayToRuleThemAll`.
* Multiply every element in `myFavorites` by two.
* Call the third element in `myFavorites` using indexing.
* Create a four element, two-by-two matrix of numbers named `TheMatrixHasYou`. 
* Access the upper left element in `TheMatrixHasYou` using indexing.
* Find the largest number in each row for `TheMatrixHasYou`.
* Reshape `TheMatrixHasYou` into a matrix with one row and four columns.

<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Caution!</h3>
    </div>
    <div class="panel-body">
        <p>Be sure to zip and submit your entire directory when finished!</p>
    </div>
</div>